### ISSUE TITLE
[code quality] Non idiomatic use of False

### ISSUE THREAD

**Issue by ilyash** [billdry/public-python-examples#1]
Quite a few places use `False` to represent absence of data. In Python, the idiomatic way would be to use `None`. It would also simplify few places that use `get(my_data, False)` - it would become `get(my_data)`, which returns None of the data is not there.

**Comment by billdry** [comment]
Switched from False to None when returning no data.

**Comment by billdry** [comment]
I made the fix described in my previous comment on this issue, made the commit to this repo & will now close this issue.

**Comment by billdry** [comment]
Fixed in commit 8fa2fadf61443e84e5ebecc506ad88bb9aadd9ea
