### ISSUE TITLE
[code quality] Unjustified use of **kwargs in get_ssm_parameter_tags()

### ISSUE THREAD

**Issue by ilyash** [billdry/public-python-examples#2]

**Comment by billdry** [comment]
Switched from kwargs to 3 arguments initialized to None

**Comment by billdry** [comment]
I made the fix described in my previous comment on this issue, made the commit to this repo & will now close this issue.

**Comment by billdry** [comment]
Fixed in commit 8fa2fadf61443e84e5ebecc506ad88bb9aadd9ea
